source 'https://github.com/CocoaPods/Specs.git'

target 'Spotlight_Example', :exclusive => true do
  pod "Spotlight", :path => "../"
end

target 'Spotlight_Tests', :exclusive => true do
  pod "Spotlight", :path => "../"

  
end
